<?php


namespace app\admin\controller;


use think\Exception;

class About extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        return $this->fetch();
    }
    public function add(){
        if(!$this->request->isPost()){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'数据请求格式错误'
            ]);
        }
            $data=$this->request->post();
            try{
                $model=model('About');
                $result=$model->inserts($data);
                if($result){
                    return json([
                        'code'=>config('code.success'),
                        'msg'=>'添加成功'
                    ]);
                }else{
                    return json([
                        'code'=>config('code.fali'),
                        'msg'=>'添加失败'
                    ]);
                }
            }catch (Exception $exception){
                return json([
                    'code'=>config('code.fali'),
                    'msg'=>'添加失败'
                ]);
            }

    }
    public function query(){
        if(!$this->request->isGet()){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'数据请求格式错误'
            ]);
        }
        $data=$this->request->get();

        try{
            $model=model('About');
            $result=$model->finds($data);
            if($result){
                return json([
                    'code'=>0,
                    'msg'=>'',
                    'data'=>$result
                ]);
            }else{
                return json([
                    'code'=>config('code.fali'),
                    'msg'=>'请求失败'
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'请求数据失败'
            ]);
        }


    }
    public function del(){
        if(!$this->request->isPost()){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'数据请求格式错误'
            ]);
        }
        $data=$this->request->post();
        $id=$data['id'];
        $model=model('About');
        $result=$model->dels(['id'=>$id]);
        try{
            if($result){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'删除成功',
                ]);
            }else{
                return json([
                    'code'=>config('code.fali'),
                    'msg'=>'删除失败'
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'删除失败'
            ]);
        }
    }
    public function edit(){
        if(!$this->request->isPost()){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'数据请求格式错误'
            ]);
        }
        $data=$this->request->post();
        try{
            $model=model('About');
            $result=$model->edits($data);
            if($result){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>"数据获取成功",
                    'data'=>$result
                ]);
            }else{
                return json([
                    'code'=>config('code.fali'),
                    'msg'=>"数据获取失败",
                ]);
            }

        }catch (Exception $exception){
            return json([
                'code'=>config('code.fali'),
                'msg'=>"数据获取失败",
            ]);
        }
    }
    public function update(){
        if(!$this->request->isPost()){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'数据请求格式错误'
            ]);
        }
        $data=$this->request->post();
        $model=model('About');
        $result=$model->updates($data);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>"修改成功",
                'data'=>$result
            ]);
        }else{
            return json([
                'code'=>config('code.fali'),
                'msg'=>"修改失败",
            ]);
        }
        try{


        }catch (Exception $exception){
            return json([
                'code'=>config('code.fali'),
                'msg'=>"数据获取失败",
            ]);
        }

    }
}