<?php


namespace app\admin\controller;


use think\Db;

class Echarts extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        return $this->fetch();
    }
    public function query(){

        $model=model('Echarts');
        $categroys=$model->querys();

        $categroy=array_map(function($v){
           return $v['username'] ;
        },$categroys);
        $catenumbers=Db::table('goods')
            ->field('count(*) as number')
            ->order('typeid','desc')
            ->group('typeid')->select();
        $catenumber=array_map(function($v){
            return $v['number'];
        },$catenumbers);
        return json([
            'categroy'=>$categroy,
            'catenum'=>$catenumber

        ]);
    }
    public function pie(){
        $model=model('Echarts');
        $categroys=$model->querys();
        $catenumbers=Db::table('goods')
            ->field('count(*) as number')
            ->order('typeid','desc')
            ->group('typeid')->select();
//        var_dump($catenumbers);
//        exit();
        $data=[];
        $cate=[];
        for ($i=0;$i<count($categroys);$i++){
            $arr=['value'=>$catenumbers[$i]['number'],'name'=>$categroys[$i]['username']];
            array_push($data,$arr);
            array_push($cate,$categroys[$i]['username']);

        }
        return json([
            'data'=>$data,
            'cate'=>$cate
        ]);
    }
}