<?php


namespace app\admin\controller;


use think\Exception;

class Order extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        return $this->fetch();
    }
    public function add(){
        if(!$this->request->isPost()){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'请求方式错误'
            ]);
        }
        $data=$this->request->post();

        if(!isset($data['username'])||empty($data['username'])){
            return json(
                ['code'=>config('code.fali'),
                'msg'=>'您的姓名必填']
            );
        }
        if(!isset($data['phone'])||empty($data['phone'])){
            return json(
                ['code'=>config('code.fali'),
                    'msg'=>'手机必填']
            );
        }
        if(!isset($data['explain'])||empty($data['explain'])){
            return json(
                ['code'=>config('code.fali'),
                    'msg'=>'手机必填']
            );
        }
        if(!isset($data['vdate'])||empty($data['vdate'])){
            return json(
                ['code'=>config('code.fali'),
                    'msg'=>'手机必填']
            );
        }
        $data['times']=$data['year'].'-'.$data['month'].'-'.$data['day'];
//        $validate=validate('Order');
//        if(!$validate->check($data)){
//            return json([
//                'code'=>config('code.fali'),
//                'msg'=>$validate->getError()
//            ]);
//        }
        try{
            $model=model('Order');
            $result=$model->inserts($data);
            if($result){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'提交成功'
                ]);
            }else{
                return json([
                    'code'=>config('code.fali'),
                    'msg'=>'数据请求失败'
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fali'),
                'msg'=>'数据请求失败'
            ]);
        }
    }
    public function query(){
        if(!$this->request->isGet()){
            return json([
                'code'=>config('code,fali'),
            'smg'=>'请求方式错误'
            ]);
        }
        $data=$this->request->get();
        if(!isset($data['page'])||empty($data['page'])){
            $page=1;
        }else{
            $page=$data['page'];
        }
        if(!isset($data['limit'])||empty($data['limit'])){
            $limit=1;
        }else{
            $limit=$data['limit'];
        }
        $sdata=[];
        if(isset($data['username'])&&!empty($data['username'])){
            $sdata['username']=['like','%'.$data['username'].'%'];
        }
        if(isset($data['phone'])&&!empty($data['phone'])){
            $sdata['phone']=['like','%'.$data['phone'].'%'];
        }
        if(isset($data['serve'])&&!empty($data['serve'])){
            $sdata['serve']=['like','%'.$data['serve'].'%'];
        }
        $model=model('Order');
        $result=$model->querys($sdata,$page,$limit);
        $count=$model->counts($sdata);
        foreach ($result as $v){
            if($v['sex']==0){
                $v['sex']='女';
            }else{
                $v['sex']='男';
            }
        }
        if($result){
            return json([
                'code'=>0,
                'msg'=>'',
                'count'=>$count,
                'data'=>$result
            ]);
        }else{
            return json([
                'code'=>1,
                'msg'=>'请求失败',
            ]);
        }
    }
}