<?php


namespace app\index\controller;


use think\Controller;
use think\Db;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        关于我们
        $about=Db::table('aboutus')->find();
        $this->assign('about',$about);
//        导航栏
        $nav=Db::table('nav')->order('sort','desc')->select();
        $this->assign('navs',$nav);
//        新闻咨询
        $news=Db::table('news')->order('id','asc')->select();
        $this->assign('news',$news);
//        $this->assign('keywords',$about['keywords']);
//        return $this->fetch();
    }
}